In [1]:

import pandas as pd
data=pd.read_csv("Salary.csv")
data.head()

            Position  Level  Salary
0   Business Analyst      1   45000
1  Junior Consultant      2   50000
2  Senior Consultant      3   60000
3            Manager      4   80000
4    Country Manager      5  110000

In [3]:
data.info

<bound method DataFrame.info of             Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000>

In [5]:

data.isnull().sum()

Position    0
Level       0
Salary      0
dtype: int64

In [7]:

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["Position"]=le.fit_transform(data["Position"])
data.head()

   Position  Level  Salary
0         0      1   45000
1         4      2   50000
2         8      3   60000
3         5      4   80000
4         3      5  110000

In [9]:

x=data[["Position","Level"]]
x.head()

   Position  Level
0         0      1
1         4      2
2         8      3
3         5      4
4         3      5

In [11]:

y=data[["Salary"]]
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [13]:

from sklearn.tree import DecisionTreeRegressor
dt=DecisionTreeRegressor()
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)